### ISSUE TITLE
Specified Oracle Java version not installed

### ISSUE THREAD

**Issue by sclausson** [salt-formulas/salt-formula-java#2]
The following pillar data results in the installation of Oracle 8u151-b12 instead of version 7.
```
java:
  environment:
    enabled: true
    version: '7'
    platform: oracle-java
    development: true
```
Steps to reproduce:
`kitchen converge oracle-jdk-7-ubuntu-xenial`
```
---
ID: download_java_source
           Function: cmd.run
               Name: curl -LOH 'Cookie: oraclelicense=accept-securebackup-cookie' 'http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz'
---
```
