### ISSUE TITLE
Java oracle 9.*.* has another "download url"

### ISSUE THREAD

**Issue by kislik** [salt-formulas/salt-formula-java#3]
if your pillar:
```
java:
  environment:
    enabled: true
    version: '9'
    release: '0.4'
    build: '11'
    platform: oracle-java
    development: true

```
map.jinja for `java_version == '9'` should be:
`{%- set source_url = 'http://download.oracle.com/otn-pub/java/jdk/' + version_name + '/' + 'c2514751926b4512b076cc82f959763f'+ '/' + oracle_file_name %}`

`java.sh` work incorrect too:
should be for java 9:
`JAVA_HOME={{ environment.java_home }}/jdk-{{environment.version}}.{{environment.release}}`
If you did it your bash enviroment `$JAVA_HOME` will work correct.
